# Generated by Django 5.2.14 on 2026-06-16 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('premium', 'Premium'), ('legendary', 'Legendary')], max_length=10, unique=True)),
                ('amount', models.PositiveIntegerField(help_text='Cost in rupees')),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['amount'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('payment_method', models.CharField(choices=[('legacy', 'Legacy'), ('google_play', 'Google Play'), ('upi', 'UPI'), ('card', 'Cards'), ('netbanking', 'Net Banking'), ('wallet', 'Wallets')], default='legacy', max_length=20)),
                ('amount', models.PositiveIntegerField(help_text='Amount in rupees')),
                ('tier', models.CharField(choices=[('premium', 'Premium'), ('legendary', 'Legendary')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.subscriptionplan')),
            ],
            options={
                'verbose_name_plural': 'Subscription Payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='subpay_user_created_idx')],
            },
        ),
    ]
