# Generated by Django 5.2.14 on 2026-05-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_tokens_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='border',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='post',
            name='style_runs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
