# Generated by Django 5.2.14 on 2026-06-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_post_border_post_duration_seconds_post_style_runs'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='canvas_image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/canvas/'),
        ),
    ]
