# Generated by Codex on 2026-06-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_post_canvas_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="background_texture",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
