# Generated by Codex on 2026-06-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_post_background_texture"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="text_image",
            field=models.ImageField(blank=True, null=True, upload_to="posts/text/"),
        ),
        migrations.AddField(
            model_name="post",
            name="text_canvas_width",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="text_canvas_height",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
