# Generated by Django 5.2.14 on 2026-06-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_email_user_google_id_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='background_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='frame_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
